version: '3'

services:
  server:
    container_name: nodejs
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    depends_on:
      - database
    links:
      - database
    ports:
      - '9000:9000'

  database:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    logging: 
      driver: none